### ISSUE TITLE
db schema

### ISSUE THREAD

**Issue by hackerjade** [evanwils/implode#1]
in posts: 
author_name should be a string? or do you mean author_id?  I would use author_id (and manually grab the name from that author on the front end)
body should be text vs. string
in comments:
same issue w author_name
post_id should be an integer

**Comment by evanwils** [comment]
Hi!

I'm thinking it should be a string, because during post creation the user
chooses their "author name" or it defaults to anonymous.

It doesn't actually relate to the logged in user's id or username.

On Mon, Oct 12, 2015 at 5:18 PM, hackerjade <notifications@github.com>
wrote:

> in posts:
> author_name should be a string? or do you mean author_id? I would use
> author_id (and manually grab the name from that author on the front end)
> body should be text vs. string
> in comments:
> same issue w author_name
> post_id should be an integer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanwils/implode/issues/1>.
>



-- 

evan

**Comment by hackerjade** [comment]
If you plan to have something similar to a dropdown of all users, so the user can choose their name, you can generate that on the frontend, but use the associated id to save the relation on the backend.  Otherwise it'll be very challenging to make active record relationships when a post belongs to a user via their name.  If it's a string, you have no foreign key for active record to find the associated user for a post.

**Comment by evanwils** [comment]
Can we discuss this if you have time today or tomorrow? I was thinking of using https://en.wikipedia.org/wiki/Imageboard#Tripcodes , for when anonymous users without accounts post. 

It would be great to have a system where posts are linked to something besides user IDs, for when there are no user IDs, and ideal if only administrators could link posts to users. 

Maybe tripcodes based on IP addresses. Does that sound like an alright idea?
